//Install the REST Client extension(Visual Studio Code) to use this for testing
//if you click the "Send Request" button you test the web app within the IDE

###Click this next to see the users information

GET http://localhost:3000/users

### Click this first to create the user

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "user1",
    "password": "password1"

}



### is allowed

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name": "user1",
    "password": "password1"

}

### is not allowed

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name": "user1",
    "password": "pass"

}